### ISSUE TITLE
createAndMergeOverlappingRanges() should support 00:00-24:00 in exceptions

### ISSUE THREAD

**Issue by marios88** [spatie/opening-hours#115] opened 2019-06-08 08:05 UTC
I was trying to pass a exception for 24 hour open
Following examples also apply to daily schedule

Using `createAndMergeOverlappingRanges` the following examples do not work

```
$opening_hours_data['exceptions']['2019-06-11']['hours'][] = '00:00-24:00';
```
```
$opening_hours_data['exceptions']['2019-06-11']['hours'][] = '00:00-00:01';
$opening_hours_data['exceptions']['2019-06-11']['hours'][] = '00:01-00:00';
```

The following works but has a minute gap

```
$opening_hours_data['exceptions']['2019-06-11']['hours'][] = '00:00-23:59';
...
$opening_hours->isOpenAt(new \DateTime('2019-06-11 23:58:10')) is TRUE
$opening_hours->isOpenAt(new \DateTime('2019-06-11 23:59:10')) is FALSE
```

Is there a way to add a rule for 24 hours open without the minute gap?
I expected the '00:00-00:01' & '00:01-00:00' rule to work but it discards the second rule

Thanks in advance

**Comment by marios88** [comment] 2019-06-08 10:42
Sample code to recreate
```
PHP 7.2.19-0ubuntu0.18.04.1
using spatie/opening-hours (2.3.1)
```
```
<?php
use \Spatie\OpeningHours\OpeningHours;

require __DIR__ . '/vendor/autoload.php';

$data = [
    'monday' => [
        'hours' =>  [
            '09:00-17:00',
        ]
    ],
    'tuesday' => [
        'hours' =>  [
            '09:00-17:00',
        ]
    ],
    'wednesday' => [
        'hours' =>  [
            '09:00-17:00',
        ]
    ],
    'thursday' => [
        'hours' =>  [
            '09:00-17:00',
        ]
    ],
    'friday' => [
        'hours' =>  [
            '09:00-17:00',
        ]
    ],
    'saturday' => [
        'hours' =>  [
            '09:00-17:00',
        ]
    ],
    'exceptions' => [
        '2019-06-11' => [
            'hours' => [
                '09:00-17:00',
                //'14:00-19:00',
            ]
        ],
        '2019-06-12' => [
            'hours' => [
                '00:00-24:00',
            ]
        ],
        '2019-06-13' => [
            'hours' => [
                '00:00-00:01',
                '00:01-24:00',
            ]
        ]
    ]
];

$opening_hours = OpeningHours::create(array_merge($data,['overflow' => true]));
var_dump($opening_hours->isOpenAt(new DateTime('2019-06-11 09:00')));// Expected TRUE got TRUE
var_dump($opening_hours->isOpenAt(new DateTime('2019-06-12 09:00')));// Expected TRUE got TRUE
var_dump($opening_hours->isOpenAt(new DateTime('2019-06-13 09:00')));// Expected TRUE got TRUE

$opening_hours = OpeningHours::createAndMergeOverlappingRanges(array_merge($data,['overflow' => true]));
var_dump($opening_hours->isOpenAt(new DateTime('2019-06-11 09:00')));// Expected TRUE got TRUE
var_dump($opening_hours->isOpenAt(new DateTime('2019-06-12 09:00')));// Expected TRUE got FALSE
var_dump($opening_hours->isOpenAt(new DateTime('2019-06-13 09:00')));// Expected TRUE got FALSE
```

**Comment by atymic** [comment] 2019-06-08 23:19
This issue is a duplicate of 
https://github.com/spatie/opening-hours/issues/113
You might want to check the discussion there.

**Comment by marios88** [comment] 2019-06-09 09:11
I dont think this is a duplicate
`OpeningHours::create` and `OpeningHours::createAndMergeOverlappingRanges`
return different results with the same input

**Comment by kylekatarnls** [comment] 2019-06-09 10:22
Indeed it's not a duplicate of #113.

```php
$openingHours = \Spatie\OpeningHours\OpeningHours::create([
  'monday' => ['09:00-12:00', '13:00-18:00'],
  'tuesday' => ['09:00-12:00', '13:00-18:00'],
  'wednesday' => ['09:00-12:00'],
  'thursday' => ['09:00-12:00', '13:00-18:00'],
  'friday' => ['09:00-12:00', '13:00-20:00'],
  'saturday' => ['09:00-12:00', '13:00-16:00'],
  'sunday' => [],
  'exceptions' => [
    '2019-06-11' => ['00:00-24:00'],
  ],
]);

var_dump($openingHours->isOpenAt(new DateTime('2019-06-11 23:59:59'))); // true
```

But if we replace `create` with `createAndMergeOverlappingRanges` the result become `false` and I'm agree it's not the expected behavior.

I will fix this point.

But definitions like this:
```php
$opening_hours_data['exceptions']['2019-06-11']['hours'][] = '00:00-00:01';
$opening_hours_data['exceptions']['2019-06-11']['hours'][] = '00:01-00:00';
```

Is not something we will support. Overflowing is not supported for `'exceptions'`, that means when defining exceptions, you should never have a range end greater than the range start like 00:01 > 00:00.

**Comment by kylekatarnls** [comment] 2019-06-09 10:44
Root cause identified: `mergeOverlappingRanges` used internally by `createAndMergeOverlappingRanges` returns ranges as `TimeRange`, then `create` properly handle both strings or `TimeRange` in days definitions but it only expect stringsin `'exceptions'`. so it cast `TimeRange` objects to strings and `strval(TimeRange::fromString('00:00-24:00'))` returns `'00:00-00:00'`

So the bug to solve is:
```php
TimeRange::fromString('00:00-24:00')->__toString()
```

Currently returns: `'00:00-00:00'`
Should return: `'00:00-24:00'`

**Comment by marios88** [comment] 2019-06-09 16:59
@kylekatarnls , thanks for the fix, maybe you should add a note in the manual that `overflow` only applies to  the weekly schedule and not exceptions

**Comment by kylekatarnls** [comment] 2019-06-10 09:14
Good news, I did not remember well. `overflow` also works for exceptions.

**Closed** 2019-06-10 09:15 UTC
Labels: bug

**Comment by kylekatarnls** [comment] 2019-06-10 09:17
2.3.2 released with the fix.
